// Persian <-> English actor name transliteration map.
// Used to dedupe actors that appear under different scripts across movies.
// Key: any known form (persian or english, lowercased, spaces collapsed)
// Value: the canonical (persian) name used as the single dedup key.

export const ACTOR_NAME_MAP: Record<string, string> = {
  // --- Hollywood / Global ---
  'leila hatami': 'لیلا حاتمی',
  'ليلا حاتمي': 'لیلا حاتمی',
  'al pacino': 'آل پاچینو',
  'robert de niro': 'رابرت دنیرو',
  'robert downey jr': 'رابرت داونی جونیور',
  'robert downey jr.': 'رابرت داونی جونیور',
  'robert downey junior': 'رابرت داونی جونیور',
  'christian bale': 'کریستین بیل',
  'leonardo dicaprio': 'لئوناردو دی‌کاپریو',
  'brad pitt': 'برد پیت',
  'tom cruise': 'تام کروز',
  'joaquin phoenix': 'واکین فینیکس',
  'matthew mcconaughey': 'متیو مک‌کانهی',
  'ryan reynolds': 'رایان رینولدز',
  'hugh jackman': 'هیو جکمن',
  'jack black': 'جک بلک',
  'amy poehler': 'امی پولر',
  'morgan freeman': 'مورگان فریمن',
  'keanu reeves': 'کیانو ریوز',
  'bruce willis': 'بروس ویلیس',
  'denzel washington': 'دنزل واشینگتن',
  'tom hanks': 'تام هنکس',
  'johnny depp': 'جانی دپ',
  'will smith': 'ویل اسمیت',
  'christopher nolan': 'کریستوفر نولان',
  'quentin tarantino': 'کوئنتین تارانتینو',
  'martin scorsese': 'مارتین اسکورسیزی',
  'steven spielberg': 'استیون اسپیلبرگ',
  'james cameron': 'جیمز کامرون',
  'david fincher': 'دیوید فینچر',
  'ridley scott': 'ریدلی اسکات',
  'tim burton': 'تیم برتون',
  'clint eastwood': 'کلینت ایستوود',
  'alfonso cuaron': 'آلفونسو کوارون',
  'bong joon ho': 'بونگ جون هو',
  'denis villeneuve': 'دنی ویلنوو',
  'daniel villeneuve': 'دنی ویلنوو',
  'cillian murphy': 'کیلین مورفی',
  'emily blunt': 'امیلی بلانت',
  'matt damon': 'مت دیمون',
  'florence pugh': 'فلورنس پیو',
  'timothee chalamet': 'تیموتی شالامی',
  'timothée chalamet': 'تیموتی شالامی',
  'zendaya': 'زندایا',
  'rebecca ferguson': 'ربکا فرگوسن',
  'javier bardem': 'خاویر باردم',
  'josh brolin': 'جاش برولین',
  'austin butler': 'آستین باتلر',
  'anne hathaway': 'آن هاتاوی',
  'ann hathaway': 'آن هاتاوی',
  'jessica chastain': 'جسیکا چستین',
  'michael caine': 'مایکل کین',
  'heath ledger': 'هیت لجر',
  'gary oldman': 'گری اولدمن',
  'marlon brando': 'مارلون براندو',
  'joe pesci': 'جو پشی',
  'shah rukh khan': 'شاهرخ خان',
  'shahrukh khan': 'شاهرخ خان',
  'amitabh bachchan': 'آمیتاب باچان',
  'salman khan': 'سلمان خان',
  'aamir khan': 'عامر خان',
  'katrina kaif': 'کاترینا کایف',
  'deepika padukone': 'دیپیکا پادوکونه',
  'priyanka chopra': 'پریانکا چوپرا',
  'ranveer singh': 'رانویر سینگ',
  'ranbir kapoor': 'رانبیر کاپور',
  'hrithik roshan': 'هریتیک روشن',
  'aishwarya rai': 'آیشواریا رای',
  'kareena kapoor': 'کارینا کاپور',
  'anushka sharma': 'آنوشکا شارما',
  'brian cranston': 'برایان کرانستون',
  'aaron paul': 'آرون پال',
  'aaron paul sturtevant': 'آرون پال',
  'bryan cranston': 'برایان کرانستون',
  'walter white': 'والتر وایت',
  'harrison ford': 'هریسون فورد',
  'mark hamill': 'مارک همیل',
  'carrie fisher': 'کری فیشر',
  'samuel l jackson': 'سموئل ال جکسون',
  'samuel jackson': 'سموئل ال جکسون',
  'scarlett johansson': 'اسکارلت جوهانسون',
  'chris hemsworth': 'کریس همسورث',
  'chris evans': 'کریس ایوانز',
  'chris pratt': 'کریس پرت',
  'robert pattinson': 'رابرت پتینسون',
  'emma stone': 'اما استون',
  'emma watson': 'اما واتسون',
  'jennifer lawrence': 'جنیفر لارنس',
  'natalie portman': 'ناتالی پورتمن',
  'keira knightley': 'کیرا نایتلی',
  'kate winslet': 'کیت وینسلت',
  'angelina jolie': 'آنجلینا جولی',
  'meryl streep': 'مریل استریپ',
  'tom hardy': 'تام هاردی',
  'idris elba': 'ایدریس البا',
  'oscars isaac': 'اسکار آیزاک',
  'oscar isaac': 'اسکار آیزاک',
  'adam driver': 'آدام درایور',
  'phoenix': 'واکین فینیکس',
  'jake gyllenhaal': 'جیک جیلنهال',
  'andrew garfield': 'اندرو گارفیلد',
  'tobey maguire': 'توبی مگوایر',
  'willem dafoe': 'ویلم دفو',
  'sam worthington': 'سم ورثینگتون',
  'zoe saldana': 'زویی سالدانا',
  'sigourney weaver': 'سیگورنی ویور',
  'michelle pfeiffer': 'میشل فایفر',
  'michael keaton': 'مایکل کیتون',
  'danny devito': 'دنی دویتو',
  'jack nicholson': 'جک نیکلسون',
  'kim basinger': 'کیم بسینگر',
  'winona ryder': 'وینونا رایدر',
  'helena bonham carter': 'هلنا بونهام کارتر',
  'penelope cruz': 'پنه‌لوپه کروز',
  'pedro pascal': 'پدرو پاسکال',
  'bella ramsey': 'بلا رمزی',
  'henry cavill': 'هنری کویل',
  'anya chalotra': 'انیا چالوترا',
  'freya allan': 'فریا آلن',
  'joey batey': 'جوی بیتی',
  'tom ellis': 'تام الیس',
  'lauren german': 'لورن آلمان',
  'kevin alejandro': 'کوین آلخاندرو',
  'd. b. woodside': 'دی بی وودساید',
  'aidan gillen': 'ایدن گیلن',
  'michael cerveris': 'مایکل سروریس',
  'adam grodman': 'آدام گرودمن',
  'trevor devall': 'ترور دیوال',
  'spencer wilding': 'اسپنسر وایلدینگ',
  'kristofer hivju': 'کریستوفر هایوجو',
  'gemma arterton': 'جما آرترتون',
  'jason statham': 'جیسون استاتهام',
  'dwayne johnson': 'دوین جانسون',
  'vin diesel': 'وین دیزل',
  'paul walker': 'پل واکر',
  'michelle rodriguez': 'میشل رودریگز',
  'tyrese gibson': 'تایریس گیبسون',
  'ludacris': 'لوداکریس',
  'gal gadot': 'گل گدوت',
  'chris pine': 'کریس پاین',
  'ben affleck': 'بن افلک',
  'ezra miller': 'ازرا میلر',
  'ray fisher': 'ری فیشر',
  'jason momoa': 'جیسون موموا',
  'amber heard': 'آمبر هرد',
  'patrick wilson': 'پاتریک ویلسون',
  'ethan hawke': 'ایتن هاوک',
  'julianne moore': 'جولیان مور',
  'tom hiddleston': 'تام هیدلستون',
  'clive owen': 'کلایو اوون',
  'gerard butler': 'جرارد باتلر',
  'milla jovovich': 'میلا یوویچ',
  'ali larter': 'علی لارتر',
  'sharlto copley': 'شارلتو کوپلی',
  'ian mcshane': 'ایان مک‌شین',
  'michael fassbender': 'مایکل فاسبندر',
  'noomi rapace': 'نومی راپاس',
  'charlize theron': 'شارلیز ترون',
  'nick frost': 'نیک فراست',
  'simon pegg': 'سایمون پگ',
  'andy serkis': 'اندی سرکیس',
  'bill nighy': 'بیل نای',
  'martin freeman': 'مارتین فریمن',
  'paddy considine': 'پدی کانسیدین',
  'eddie marsan': 'ادی مارشن',
  'vinnie jones': 'وینی جونز',
  'jason flemyng': 'جیسون فلمینگ',
  'mark strong': 'مارک استرانگ',
  'stephen graham': 'استفن گراهام',
  'lena headey': 'لنا هیدی',
  'peter dinklage': 'پیتر دینکلیج',
  'nikolaj coster-waldau': 'نیکلای کستر-والدو',
  'emilia clarke': 'امیلیا کلارک',
  'kit harrington': 'کیت هرینگتون',
  'sophie turner': 'سوفی ترنر',
  'maisie williams': 'میسی ویلیامز',
  'bran stark': 'برن استارک',
  'arya stark': 'آریا استارک',
  'jon snow': 'جان اسنو',
  'daenerys targaryen': 'دنریس تارگرین',
  'tyrion lannister': 'تیریون لنیستر',
  'cersei lannister': 'سرسی لنیستر',
  'jaime lannister': 'جیمی لنیستر',
  'sansa stark': 'سانسا استارک',
  'tywin lannister': 'تایوین لنیستر',
  'brienne of tarth': 'برین تارت',
  'davos seaworth': 'داووس سیورث',
  'samwell tarly': 'سمول تارلی',
  'brandon stark': 'برن استارک',
  'sandor clegane': 'سندور کلگین',
  'the hound': 'سگ شکاری',
  'the mountain': 'کوهستان',
  'varys': 'واریس',
  'tyrion': 'تیریون لنیستر',
  'jorah mormont': 'جورا مورمونت',
  'grey worm': 'کرم خاکستری',
  'missandei': 'میساندی',
  'brienne': 'برین تارت',
  'ygritte': 'ایگریت',
  'tormund': 'تورموند',
  'gilly': 'جیلی',
  'melisandre': 'ملیساندره',
  'arya': 'آریا استارک',
  'bran': 'برن استارک',
  'sansa': 'سانسا استارک',
  'sam': 'سمول تارلی',
  'jon': 'جان اسنو',
  'daenerys': 'دنریس تارگرین',
  'cersei': 'سرسی لنیستر',
  'jaime': 'جیمی لنیستر',
  'littlefinger': 'انگشت کوچک',
  'ramsay bolton': 'رَمزی بولتون',
  'robb stark': 'راب استارک',
  'catlyn stark': 'کتلین استارک',
  'catelyn stark': 'کتلین استارک',
  'robert baratheon': 'رابرت براتیون',
  'ned stark': 'ادارد استارک',
  'eddard stark': 'ادارد استارک',
  'robin arryn': 'رابین آرین',
  'bronze yohn royce': 'برنز یوهن رویس',
  'lord baffles': 'لرد بافلز',
  'hodor': 'هودور',
  'rickon stark': 'ریکون استارک',
  'rickard stark': 'ریکارد استارک',
  'benjen stark': 'بنجن استارک',
  'lyanna stark': 'لینا استارک',
  'howland reed': 'هولند رید',
  'meera reed': 'میرا رید',
  'jojen reed': 'جوجن رید',
  'craster': 'کرستر',
  'gillys baby': 'بچه جیلی',
  'val': 'وال',
  'ysa': 'ایسا',
  'shaggydog': 'سگ پشمالو',
  'summer': 'تابستان',
  'ghost': 'روح',
  'nymeria': 'نیمریا',
  'lady': 'بانو',
  'grey wind': 'باد خاکستری',
  'theon greyjoy': 'تئون گریجوی',
  'yara greyjoy': 'یارا گریجوی',
  'balon greyjoy': 'بالون گریجوی',
  'euron greyjoy': 'یورون گریجوی',
  'victarion greyjoy': 'ویکتاریون گریجوی',
  'asha greyjoy': 'آشا گریجوی',
  'rodrik greyjoy': 'رودریک گریجوی',
  'margaery tyrell': 'مارجري تایرل',
  'loras tyrell': 'لوراس تایرل',
  'mace tyrell': 'میس تایرل',
  'olenna tyrell': 'النا تایرل',
  'podrick payne': 'پودریک پین',
  'tarly': 'تارلی',
  'edmure tully': 'ادمور تالی',
  'catlyn': 'کتلین استارک',
  'catelyn': 'کتلین استارک',
  'brynden tully': 'بریندن تالی',
  'blackfish': 'ماهی سیاه',
  'harrold hardyng': 'هارولد هاردینگ',
  'robert arryn': 'رابرت آرین',
  'lysax': 'لیسا',
  'lysa arryn': 'لیسا آرین',
  'jon arryn': 'جان آرین',
  'hoster tully': 'هوستر تالی',
  'walder frey': 'والدر فری',
  'frey': 'فری',
  'meryn trant': 'مرین ترانت',
  'barristan selmy': 'باریستان سلمی',
  'selmy': 'سلمی',
  'quaithe': 'کوایت',
  'xaro xhoan daxos': 'زارو خوان داکسوس',
  'pyat pree': 'پیات پری',
  'j quantification': 'جی',
  'jaqen hghar': 'جاکن هغار',
  'faceless man': 'مرد بی‌چهره',

  // --- Iranian ---
  'shahab hosseini': 'شهاب حسینی',
  'shahab hossaini': 'شهاب حسینی',
  'peyman maadi': 'پیمان معادی',
  'taraneh alidoosti': 'ترانه علیدوستی',
  'taraneh ali doosti': 'ترانه علیدوستی',
  'sareh bayat': 'ساره بیات',
  'sarah bayat': 'ساره بیات',
  'merila zarei': 'مریلا زارعی',
  'navid mohammadzadeh': 'نوید محمدزاده',
  'parinaz izadyar': 'پریناز ایزدیار',
  'houtan shakiba': 'هوتن شکیبا',
  'reza attaran': 'رضا عطاران',
  'asghar farhadi': 'اصغر فرهادی',
  'bahram afshari': 'بهرام افشاری',
  'pantea bahram': 'پانته‌آ بهرام',
  'babak karimi': 'بابک کریمی',
  'amir hossein fathi': 'امیرحسین فتحی',
  'emir hossein fathi': 'امیرحسین فتحی',
  'iman safa': 'ایمان صفا',
  'sadegh hedayati': 'صادق هدایت',
  'saed hedayati': 'سعید هدایتی',
  'nader soleimani': 'نادر سلیمانی',
  'omid roohani': 'امید روهانی',
  'soheil ghanadan': 'سهیل قنادان',
  'amin aminem': 'امین امینم',
  'masoud roohnikan': 'مسعود روه‌نیکان',
  'mohammad javad jafarpour': 'محمدجواد جعفرپور',
  'siamak ansari': 'سیامک انصاری',
  'mahnaz afshar': 'ماهناز افشار',
  'hedieh tehrani': 'هدیه تهرانی',
  'fereshteh sadre orfani': 'فرشته صدرعرفانی',
  'golshifteh farahani': 'گلشیفته فراهانی',
  'fatemeh motamed arya': 'فاطمه معتمدآریا',
  'baran kosari': 'باران کوثری',
  'hana aghighi': 'هانا آقایی',
  'tannaz tabatabaei': 'تناز تبریزی',
  'saber abar': 'صابر ابر',
  'payman maadi': 'پیمان معادی',
  'homayoun erdost': 'همایون اردست',
  'homayoun shajarian': 'همایون شجریان',
  'mohsen tanabandeh': 'محسن تنابنده',
  'ahmad mehranfar': 'احمد مهرانفر',
  'alireza khamseh': 'علیرضا خمسه',
  'falamak joneidi': 'فلامک جونیدی',
  'shaghayegh dehghan': 'شقایق دهقان',
  'mohammad reza golzar': 'محمدرضا گلزار',
  'reza ghoochaninejad': 'رضا قوچان‌نژاد',
  'ali nasirian': 'علی نصیریان',
  'ezatollah enemi': 'عزت‌الله انتظامی',
  'jamshid mashayekhi': 'جمشید مشایخی',
  'dariush arjmand': 'داریوش ارجمند',
  'parviz parastui': 'پرویز پرستویی',
  'reza kianian': 'رضا کیانیان',
  'akbar abdi': 'اکبر عبدی',
  'fatemeh goudarzi': 'فاطمه گودرزی',
  'mitra hajjar': 'میترا حجار',
  'elaheh hashemi': 'الهه هاشمی',
  'shila khodadad': 'شیلا خداداد',
  'linda kiani': 'ليندا کیانی',
  'nazanin bayat': 'نازنین بیات',
  'nazanin morshedi': 'نازنین مشرقی',
  'sogol khaligh': 'ثگل خلیلی',
  'sogol khalili': 'ثگل خلیلی',
  'ghogha bayat': 'ققا بیات',
  'goga bayat': 'ققا بیات',
  'shohreh aghdashloo': 'شهره آغداشلو',
  'shohreh aghdashlo': 'شهره آغداشلو',
  'behrouz vossoughi': 'بهروز وثوقی',
  'googoosh': 'گوگوش',
  'faramarz gharibian': 'فرامرز قریبیان',
  'bahman farmanara': 'بهمن فرمان‌آرا',
  'khosro shakibai': 'خسرو شکیبایی',
  'saeed rad': 'سعید راد',
  'hassan pourshirazi': 'حسن پورشیرازی',
  'ghorban ahmadi galdi': 'قربان احمدی گلده',
  'mehran modiri': 'مهران مدیری',
  'hasan khajasti': 'حسن خجسته',
  'mohammad reza shahidipour': 'محمدرضا شهیدی‌پور',
  'sina motallebi': 'سینا مطلبی',
  'maryam palizban': 'مریم پالیزبان',

  // --- Turkish ---
  'halit ergenç': 'خالد ارگنچ',
  'meryem uzerli': 'مریم اوزرلی',
  'beren saat': 'بهره‌ن ساعت',
  'kivanç tatlitug': 'کیوانچ تاتلیتوغ',
  'engin akyürek': 'انگین آکیورک',
  'tuba büyüküstün': 'توبا بویوک‌اوستون',
  'nurgül yesilçay': 'نورگل یشیل‌چای',
  'ozan güven': 'اوزان گوون',
  'selin demiratar': 'سلین دمیراتار',
  'caner çilingir': 'جانر چیلینگیر',
  'barış arduç': 'باریش آردوچ',
  'ayça ayşin turan': 'آیچا آیشین توران',
  'hazar ersoy': 'هزار ارسوی',
  'serkan çayoğlu': 'سرکان چای‌اوغلو',
  'hande erçel': 'هانده ارچل',
  'cem yiğit üzümoğlu': 'جما ییگیت اوزوم‌اوغلو',
  'arda erik': 'آردا اریک',
  'sarp apak': 'سارپ آپاک',
  'serkan keskin': 'سرکان کسکین',
  'öner erkan': 'اونر ارکان',
  'kıvanç tatlıtuğ': 'کیوانچ تاتلیتوغ',
  'özge özberk': 'اوزگه اوزبرک',
  'onur saylak': 'اونور سایلاک',
  'pelin karahan': 'پلین کاراهان',
  'boran kuzum': 'بوران کوزوم',
  'miray daner': 'میرای دانر',
  'aslı enver': 'اصلی انور',
  'burak özçivit': 'بوراک اوzcivit',
  'demet özdemir': 'دمت اوزدمیر',
  'can yaman': 'جان یامان',
  'ibrahim çelikkol': 'ابراهیم چلیک‌کول',
  'öykü karayel': 'اوی‌کو کارایل',
  'funda eryigit': 'فوندا اریگیت',
  'mehmet ali nuroğlu': 'محمدعلی نوراوغلو',
  'kerem bürsin': 'کرم بورسین',
  'hande doğandemir': 'هانده دوغان‌دیمیر',
  'çagatay ulusoy': 'چاغاتای اولوسوی',
  'maraşlı': 'ماراشلی',
  'sadiq bey': 'صدیق بیگ',
  'kerem aktürkoğlu': 'کرم آکتورک‌اوغلو',
  'yildiz çagri atiksoy': 'ییلدیز چاغری آتیک‌سوی',
  'erkan kolçak köstendil': 'ارکان کولچاک کوستندیل',
  'rıza kocaoğlu': 'ریزا کوجا‌اوغلو',
  'gökhan alkan': 'گوکهان آلکان',
  'damla sönmez': 'داملا سونمز',
  'nesrin cavadzade': 'نسرین جوادزاده',
  'gülçin santırcıoğlu': 'گولچین سانتیرجی‌اوغلو',
  'aytaç şaşmaz': 'آیتاچ شاشماز',
  'meltem akçöl': 'ملتم آکچول',
  'batuhan özkan': 'باتوهان اوزکان',
  'cihan inan': 'جیهان اینان',
  'mert doğan': 'مرت دوغان',
  'eda ece': 'ادا اجه',
  'cigdem belci': 'چیگدم بلجی',
  'sinan helvaci': 'سینان حلواچی',
  'ali seçkiner alıcı': 'علی سچکینر آلیجی',
  'elif nur kaya': 'الیف نور کایا',
  'cansu cihan': 'جانسو جیهان',
  'esra inal': 'اسرا اینال',
  'sumru yavrucuk': 'سومرو یاورجوک',
  'raziye gonder': 'رازیه گوندر',
  'elif caraci': 'الیف جاراجی',
  'deniz can aktas': 'دنیز جان آکتاش',
  'erkan petekkaya': 'ارکان پتک‌کایا',
  'nilperi şahinkaya': 'نیلپری شاهین‌کایا',
  'öznur serçeler': 'اوزنور سرچلر',
  'burak tosun': 'بوراک توشون',
  'defne kayalar': 'دفنه کایالار',
  'alp navruz': 'آلپ ناوروز',
  'feyza sevil güngör': 'فیزا سویل گونگور',
  'ahmet tansu taşanlar': 'احمد تانسو تاشانلار',
  'necati şaşmaz': 'نجاتی شاشماز',
  'gürkan utanır': 'گورکان اوتانیر',
  'aybuke pusat': 'آی‌بوکه پوسات',
  'buse varol': 'بوسه وارول',
  'sinem unsal': 'سینم اونسال',
  'emre bey': 'امره بیگ',
  'elif ceren balıkçı': 'الیف جرن بالیکچی',
  'emir özbatur': 'امیر اوزباتور',
  'cafer doğan': 'جعفر دوغان',
  'hans zimmer': 'هانس زیمر',
  'clancy brown': 'کلنسی براون',
  'clancy brown (mr krabs)': 'کلنسی براون (آقای خرچنگ)',
  'anna sawai': 'آنا ساوای',
  'cosmo jarvis': 'کازمو جارویس',
  'al martino': 'آل مارتینو',
  'abe vigoda': 'ایب ویگودا',
  'al lettieri': 'آل لتییری',
  'bruno kirby': 'برونو کربی',
  'diane keaton': 'دایان کیتون',
  'harvey keitel': 'هاروی کایتل',
  'andy garcia': 'اندی گارسیا',
  'eli wallach': 'الی والاک',
  'bridget fonda': 'بریجت فوندا',
  'talie shire': 'تالیا شایر',
  'joe mantegna': 'جو مانtegna',
  'billy dee williams': 'بیلی دی ویلیامز',
  'pat hingle': 'پت هینگل',
  'michael gough': 'مایکل گاف',
  'michael murphy': 'مایکل مورفی',
  'robert wuhl': 'رابرت وول',
  'tom berenger': 'تام برنجر',
  'james whitmore': 'جیمز وایتمور',
  'mark rolston': 'مارک رولستون',
  'gil bellows': 'گیل بلوز',
  'bill irwin': 'بیل اروین',
  'ayo edebiri': 'آیو ادبیری',
  'lola petticrew': 'لولا پتیکرو',
  'quincy tyler bernstine': 'کوئینسی تایلر برنستاین',
  'gabriela petry': 'گابریلیا پتری',
  'adriano toloza': 'آدریانو تولوزا',
  'brian libby': 'برایان لیبی',
  'dileep rao': 'دیلیپ رائو',
  'david gyasi': 'دیوید گیاسی',
  'sam nouri': 'سم نوری',
  'behrang alavi': 'بهرنگ علوی',
  'siavash cheraghipour': 'سیاوش چراغی‌پور',
  'seyed javad hashemi': 'سید جواد هاشمی',
  'naimeh nezamdoost': 'نعیمه نظام‌دوست',
  'larry brandenburg': 'لری برندنبورگ',
  'neil giuntoli': 'نیل جیونتولی',
  'amanda plummer': 'آماندا پلامر',
  'maria de medeiros': 'ماریا دو مدیروس',
  // --- Additional from castAndAwardsDatabase (English -> Persian) ---
  "ludwig goransson": "لودویگ گورانسون",
  "ludwig göransson": "لودویگ گورانسون",
  "hoyte van hoytema": "هویته ون هویتما",
  "matt reeves": "مت ریوز",
  "michael giacchino": "مایکل جیاکینو",
  "colin farrell": "کالین فارل",
  "todd phillips": "تاد فیلیپس",
  "shawn levy": "شان لوی",
  "saman moghaddam": "سامان مقدم",
  "sahar dolatshahi": "سحر دولتشاهی",
  "amir tavassoli": "امیر توسلی",
  "pardis ahmadieh": "پردیس احمدیه",
  "jamshid mahmoudi": "جمشید محمودی",
  "bamdad afshar": "بامداد افشار",
  "hadi hejazifar": "هادی حجازیفر",
  "alireza kamali": "علیرضا کمالی",
  "karim amini": "کریم امینی",
  "ebrahim amerian": "سید ابراهیم عامریان",
  "hadi kazemi": "هادی کاظمی",
  "elnaz habibi": "الناز حبیبی",
  "hassan fathi": "حسن فتحی",
  "mehdi soltani": "مهدی سلتانی",
  "mahmoud pakniyat": "محمود پاکنیت",
  "mahmoud kalari": "محمود کلاری",
  "gelareh abbasi": "گلاره عباسی",
  "roya nonahali": "رویا نونهالی",
  "sarina farhadi": "سارینا فرهادی",
  "mohsen chavoshi": "محسن چاوشی",
  "mostafa zamani": "مصطفی زمانی",
  "hayedeh safiyari": "هایده صفییاری",
  "hiroyuki sanada": "هیرویوکی سانادا",
  "ken watanabe": "کن واتانابه",
  "marion cotillard": "ماریون کوتیار",
  "aaron eckhart": "آرون اکهارت",
  "maggie gyllenhaal": "مگی جیلنهال",
  "emma corrin": "اما کورین",
  "morena baccarin": "مورنا باکارین",
  "elliot page": "الیوت پیج",
  "joseph gordon-levitt": "جوزف گوردون لویت",
  "mackenzie foy": "مکنزی فوی",
  "bob odenkirk": "باب اودنکرک",
  "anna gunn": "آنا گان",
  "dean norris": "دین نوریس",
  "jonathan banks": "جاناتان بنکس",
  "giancarlo esposito": "جانکارلو اسپوزیتو",
  "vince gilligan": "وینس گیلیگان",
  "hildur gudnadottir": "هیلدور گودنادوتیر",
  "maya hawke": "مایا هاوک",
  "lewis black": "لوئیس بلاک",
  "tony hale": "تونی هیل",
  "phyllis smith": "فیلیس سمیت",
  "kelsey mann": "کلسی من",
};

// Reverse-index so lookups work both directions (english->persian and persian->english)
export const REVERSE_ACTOR_NAME_MAP: Record<string, string> = (() => {
  const rev: Record<string, string> = {};
  for (const [k, v] of Object.entries(ACTOR_NAME_MAP)) {
    // map canonical persian -> english form too (for english lookups when key is persian)
    if (k !== v) rev[v] = k;
  }
  return rev;
})();

export function resolveActorCanonicalKey(name?: string): string | null {
  if (!name) return null;
  const n = name.trim().toLowerCase().replace(/\s+/g, " ");
  if (!n) return null;
  if (ACTOR_NAME_MAP[n]) return ACTOR_NAME_MAP[n];
  // REMOVED: reverse lookup was returning English for Persian input, breaking dedup & display
  return null;
}
